### ISSUE TITLE
SPI buffer size

### ISSUE THREAD

**Issue by MichalKochman** [TuryRx/Banana-pi-m2-zero-GPIO#6]
Hi,
I am sorry to "spam" you like this. However I am trying to increase the SPI buffer, as it seems many before me.
I have managed to enable the spi and I2C following your advices in your repos, but I am failing to set different buffer size than 4096.

I Have tried both unload the module and load it with parameter (modprobe spidev bufsiz=8192), added "param_spidev_bufsize=20480" to armbianEnv.txt; but no help.

My armbianEnv looks like this:
```
verbosity=8
bootlogo=false
console=both
#disp_mode=1920x1080p60
disp_mode=1280x720p60
overlay_prefix=sun8i-h3
rootdev=UUID=76ad07d8-a310-4dd0-9975-1a3ebf4cd0b4
rootfstype=ext4
overlays=i2c0 spi-add-cs1 spi-jedec-nor spi-spidev
param_spidev_spi_bus=0
param_spidev_bufsize=20480
usbstoragequirks=0x2537:0x1066:u,0x2537:0x1068:u
```

Could you help? Thanks (I would not even get this far withou your repos).

**Comment by MichalKochman** [comment]
Solved, need to add line "extraargs=spidev.bufsiz=8192" to armbianEnv
(see https://teamgloomy.github.io/dsf_on_armbian.html)

**Comment by TuryRx** [comment]
I'm glad you were able to solve it friend, I'm really sorry for taking so long to see your message but then I'm very busy with work
